#!/usr/bin/env python3
"""Deterministic WebMCP adapter generation.

This module only generates browser adapters around real application handlers.
Repository-specific business logic is deliberately outside the generator: the
product compiler and agent workflow must implement and verify those operations
before an adapter can be considered ready.
"""

from __future__ import annotations

import json
from typing import Any


CODEGEN_VERSION = "3.0.0"

SUPPORTED_TARGETS = (
    "vanilla-js",
    "typescript",
    "react",
    "next",
    "vue",
    "svelte",
    "angular",
)


class CodegenError(ValueError):
    """Raised when a requested target or profile cannot be generated."""


def _descriptors(manifest: dict[str, Any]) -> list[dict[str, Any]]:
    descriptors: list[dict[str, Any]] = []
    for item in manifest.get("tools", []):
        descriptor: dict[str, Any] = {
            "name": item["name"],
            "description": item["description"],
            "inputSchema": item["inputSchema"],
            "annotations": item["annotations"],
            "handler": item["handler"],
            "registration": {
                "exposedTo": item.get("registration", {}).get("exposedTo", []),
            },
        }
        if "title" in item:
            descriptor["title"] = item["title"]
        descriptors.append(descriptor)
    return descriptors


def _descriptor_json(manifest: dict[str, Any]) -> str:
    return json.dumps(
        _descriptors(manifest),
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
    )


def generate_javascript(manifest: dict[str, Any], manifest_hash: str) -> str:
    """Generate the framework-neutral JavaScript publisher."""

    descriptors = _descriptor_json(manifest)
    return f'''// Generated by webmcp-codegen {CODEGEN_VERSION}.
// Manifest SHA-256: {manifest_hash}
// Build-time semantics are intentionally omitted from browser registration.
// Bind only real application operations; this file does not invent business logic.

export const WEBMCP_MANIFEST_SHA256 = "{manifest_hash}";
const TOOL_DESCRIPTORS = Object.freeze({descriptors});

export const WEBMCP_TOOL_NAMES = Object.freeze(
  TOOL_DESCRIPTORS.map((descriptor) => descriptor.name),
);

function abortReason(signal) {{
  if (signal && "reason" in signal && signal.reason !== undefined) {{
    return signal.reason;
  }}
  return new DOMException("The operation was aborted.", "AbortError");
}}

function jsonValueError(path, message) {{
  return new TypeError(`WebMCP result is not JSON-safe at ${{path}}: ${{message}}`);
}}

/**
 * Assert an intentional JSON value without relying on lossy JSON.stringify coercion.
 * @param {{unknown}} value
 * @param {{string}} path
 * @param {{Set<object>}} seen
 * @returns {{unknown}}
 */
export function assertWebMCPJSONValue(value, path = "$", seen = new Set()) {{
  if (value === null) return value;
  const kind = typeof value;
  if (kind === "string" || kind === "boolean") return value;
  if (kind === "number") {{
    if (!Number.isFinite(value)) throw jsonValueError(path, "number must be finite");
    return value;
  }}
  if (kind !== "object") {{
    throw jsonValueError(path, `unsupported ${{kind}} value`);
  }}
  if (seen.has(value)) throw jsonValueError(path, "cyclic reference");
  seen.add(value);
  try {{
    if (Array.isArray(value)) {{
      if (Object.getOwnPropertySymbols(value).length > 0) {{
        throw jsonValueError(path, "symbol-keyed array properties are unsupported");
      }}
      const ownNames = Object.getOwnPropertyNames(value);
      const expectedNames = [
        ...Array.from({{ length: value.length }}, (_, index) => String(index)),
        "length",
      ];
      if (ownNames.length !== expectedNames.length ||
          expectedNames.some((name) => !ownNames.includes(name))) {{
        throw jsonValueError(path, "arrays must be dense and have no extra properties");
      }}
      for (let index = 0; index < value.length; index += 1) {{
        assertWebMCPJSONValue(value[index], `${{path}}[${{index}}]`, seen);
      }}
      return value;
    }}

    const prototype = Object.getPrototypeOf(value);
    if (prototype !== Object.prototype && prototype !== null) {{
      const name = value?.constructor?.name ?? "object";
      throw jsonValueError(path, `${{name}} instances must be converted to plain data`);
    }}
    if (Object.getOwnPropertySymbols(value).length > 0) {{
      throw jsonValueError(path, "symbol-keyed object properties are unsupported");
    }}
    const enumerableNames = Object.keys(value);
    const ownNames = Object.getOwnPropertyNames(value);
    if (ownNames.length !== enumerableNames.length ||
        ownNames.some((name) => !enumerableNames.includes(name))) {{
      throw jsonValueError(path, "object properties must be enumerable JSON fields");
    }}
    for (const [key, child] of Object.entries(value)) {{
      assertWebMCPJSONValue(child, `${{path}}.${{key}}`, seen);
    }}
    return value;
  }} finally {{
    seen.delete(value);
  }}
}}

export function requireWebMCPHandlers(handlers, names = TOOL_DESCRIPTORS.map((item) => item.handler)) {{
  if (!handlers || typeof handlers !== "object") {{
    throw new TypeError("handlers must be an object keyed by manifest handler names");
  }}
  for (const name of names) {{
    if (typeof handlers[name] !== "function") {{
      const descriptor = TOOL_DESCRIPTORS.find((item) => item.handler === name);
      const suffix = descriptor ? ` for ${{descriptor.name}}` : "";
      throw new TypeError(`Missing WebMCP application handler: ${{name}}${{suffix}}`);
    }}
  }}
  return handlers;
}}

export function createWebMCPHandlerDelegates(getHandlers, names) {{
  if (typeof getHandlers !== "function") {{
    throw new TypeError("getHandlers must be a function");
  }}
  requireWebMCPHandlers(getHandlers(), names);
  return Object.fromEntries(
    names.map((name) => [
      name,
      (input, context) => {{
        const handlers = requireWebMCPHandlers(getHandlers(), [name]);
        return handlers[name](input, context);
      }},
    ]),
  );
}}

/** Register the generated toolset against real application handlers. */
export async function registerWebMCPTools(handlers, options = {{}}) {{
  requireWebMCPHandlers(handlers);

  const modelContext = globalThis.document?.modelContext;
  if (typeof modelContext?.registerTool !== "function") {{
    return Object.freeze({{
      supported: false,
      registered: Object.freeze([]),
      dispose() {{}},
    }});
  }}

  const controller = new AbortController();
  const externalSignal = options?.signal;
  let externalAbortListener = null;
  if (externalSignal) {{
    if (externalSignal.aborted) throw abortReason(externalSignal);
    externalAbortListener = () => controller.abort(abortReason(externalSignal));
    externalSignal.addEventListener("abort", externalAbortListener, {{ once: true }});
  }}

  const cleanupExternalListener = () => {{
    if (externalSignal && externalAbortListener) {{
      externalSignal.removeEventListener("abort", externalAbortListener);
      externalAbortListener = null;
    }}
  }};

  const registered = [];
  try {{
    for (const descriptor of TOOL_DESCRIPTORS) {{
      const registrationOptions = {{ signal: controller.signal }};
      if (descriptor.registration.exposedTo.length > 0) {{
        registrationOptions.exposedTo = [...descriptor.registration.exposedTo];
      }}
      await modelContext.registerTool(
        {{
          name: descriptor.name,
          ...(descriptor.title !== undefined ? {{ title: descriptor.title }} : {{}}),
          description: descriptor.description,
          inputSchema: descriptor.inputSchema,
          annotations: descriptor.annotations,
          execute: async (input, executionOptions) => {{
            const signal = executionOptions?.signal;
            if (signal?.aborted) throw abortReason(signal);
            const currentHandlers = requireWebMCPHandlers(handlers, [descriptor.handler]);
            const result = await currentHandlers[descriptor.handler](input, {{
              signal,
              toolName: descriptor.name,
            }});
            assertWebMCPJSONValue(result);
            JSON.stringify(result);
            return result;
          }},
        }},
        registrationOptions,
      );
      registered.push(descriptor.name);
    }}
  }} catch (error) {{
    controller.abort(error);
    cleanupExternalListener();
    throw error;
  }}

  let disposed = false;
  return Object.freeze({{
    supported: true,
    registered: Object.freeze([...registered]),
    signal: controller.signal,
    dispose(reason) {{
      if (disposed) return;
      disposed = true;
      controller.abort(reason);
      cleanupExternalListener();
    }},
  }});
}}
'''


def _typescript_runtime(
    manifest: dict[str, Any],
    manifest_hash: str,
    *,
    next_client: bool = False,
) -> str:
    descriptors = _descriptor_json(manifest)
    client_directive = '\n"use client";\n' if next_client else ""
    return f'''/// <reference types="webmcp-types" />{client_directive}
// Generated by webmcp-codegen {CODEGEN_VERSION}.
// Manifest SHA-256: {manifest_hash}
// Bind only real application operations; this file does not invent business logic.

export const WEBMCP_MANIFEST_SHA256 = "{manifest_hash}";
const TOOL_DESCRIPTORS = {descriptors} as const;

export type JSONValue = null | boolean | string | number | JSONValue[] | {{ [key: string]: JSONValue }};
export type ToolExecutionContext = Readonly<{{ signal: AbortSignal; toolName: string }}>;
export type WebMCPHandler = (
  input: Record<string, unknown>,
  context: ToolExecutionContext,
) => unknown | Promise<unknown>;
export type WebMCPHandlers = Record<string, WebMCPHandler>;
export type WebMCPRegistration = Readonly<{{
  supported: boolean;
  registered: readonly string[];
  signal?: AbortSignal;
  dispose(reason?: unknown): void;
}}>;

function abortReason(signal: AbortSignal): unknown {{
  return signal.reason ?? new DOMException("The operation was aborted.", "AbortError");
}}

function jsonValueError(path: string, message: string): TypeError {{
  return new TypeError(`WebMCP result is not JSON-safe at ${{path}}: ${{message}}`);
}}

export function assertWebMCPJSONValue(
  value: unknown,
  path = "$",
  seen: Set<object> = new Set(),
): asserts value is JSONValue {{
  if (value === null) return;
  const kind = typeof value;
  if (kind === "string" || kind === "boolean") return;
  if (kind === "number") {{
    if (!Number.isFinite(value)) throw jsonValueError(path, "number must be finite");
    return;
  }}
  if (kind !== "object") throw jsonValueError(path, `unsupported ${{kind}} value`);
  const objectValue = value as object;
  if (seen.has(objectValue)) throw jsonValueError(path, "cyclic reference");
  seen.add(objectValue);
  try {{
    if (Array.isArray(value)) {{
      if (Object.getOwnPropertySymbols(value).length > 0) {{
        throw jsonValueError(path, "symbol-keyed array properties are unsupported");
      }}
      const ownNames = Object.getOwnPropertyNames(value);
      const expectedNames = [
        ...Array.from({{ length: value.length }}, (_, index) => String(index)),
        "length",
      ];
      if (ownNames.length !== expectedNames.length ||
          expectedNames.some((name) => !ownNames.includes(name))) {{
        throw jsonValueError(path, "arrays must be dense and have no extra properties");
      }}
      value.forEach((child, index) =>
        assertWebMCPJSONValue(child, `${{path}}[${{index}}]`, seen));
      return;
    }}
    const prototype = Object.getPrototypeOf(objectValue);
    if (prototype !== Object.prototype && prototype !== null) {{
      const name = (objectValue as {{ constructor?: {{ name?: string }} }}).constructor?.name ?? "object";
      throw jsonValueError(path, `${{name}} instances must be converted to plain data`);
    }}
    if (Object.getOwnPropertySymbols(objectValue).length > 0) {{
      throw jsonValueError(path, "symbol-keyed object properties are unsupported");
    }}
    const enumerableNames = Object.keys(objectValue);
    const ownNames = Object.getOwnPropertyNames(objectValue);
    if (ownNames.length !== enumerableNames.length ||
        ownNames.some((name) => !enumerableNames.includes(name))) {{
      throw jsonValueError(path, "object properties must be enumerable JSON fields");
    }}
    for (const [key, child] of Object.entries(objectValue)) {{
      assertWebMCPJSONValue(child, `${{path}}.${{key}}`, seen);
    }}
  }} finally {{
    seen.delete(objectValue);
  }}
}}

export function requireWebMCPHandlers(
  handlers: WebMCPHandlers,
  names: readonly string[] = TOOL_DESCRIPTORS.map((item) => item.handler),
): WebMCPHandlers {{
  if (!handlers || typeof handlers !== "object") {{
    throw new TypeError("handlers must be an object keyed by manifest handler names");
  }}
  for (const name of names) {{
    if (typeof handlers[name] !== "function") {{
      const descriptor = TOOL_DESCRIPTORS.find((item) => item.handler === name);
      const suffix = descriptor ? ` for ${{descriptor.name}}` : "";
      throw new TypeError(`Missing WebMCP application handler: ${{name}}${{suffix}}`);
    }}
  }}
  return handlers;
}}

export function createWebMCPHandlerDelegates(
  getHandlers: () => WebMCPHandlers,
  names: readonly string[],
): WebMCPHandlers {{
  if (typeof getHandlers !== "function") throw new TypeError("getHandlers must be a function");
  requireWebMCPHandlers(getHandlers(), names);
  return Object.fromEntries(
    names.map((name) => [
      name,
      (input: Record<string, unknown>, context: ToolExecutionContext) => {{
        const handlers = requireWebMCPHandlers(getHandlers(), [name]);
        return handlers[name](input, context);
      }},
    ]),
  ) as WebMCPHandlers;
}}

export async function registerWebMCPTools(
  handlers: WebMCPHandlers,
  options: WebMCP.ModelContextRegisterToolOptions = {{}},
): Promise<WebMCPRegistration> {{
  requireWebMCPHandlers(handlers);
  const modelContext = typeof document === "undefined" ? undefined : document.modelContext;
  if (typeof modelContext?.registerTool !== "function") {{
    return Object.freeze({{
      supported: false,
      registered: Object.freeze([]),
      dispose() {{}},
    }});
  }}

  const controller = new AbortController();
  const externalSignal = options.signal;
  let externalAbortListener: (() => void) | undefined;
  if (externalSignal) {{
    if (externalSignal.aborted) throw abortReason(externalSignal);
    externalAbortListener = () => controller.abort(abortReason(externalSignal));
    externalSignal.addEventListener("abort", externalAbortListener, {{ once: true }});
  }}
  const cleanupExternalListener = () => {{
    if (externalSignal && externalAbortListener) {{
      externalSignal.removeEventListener("abort", externalAbortListener);
      externalAbortListener = undefined;
    }}
  }};

  const registered: string[] = [];
  try {{
    for (const descriptor of TOOL_DESCRIPTORS) {{
      const registrationOptions: WebMCP.ModelContextRegisterToolOptions = {{
        signal: controller.signal,
      }};
      if (descriptor.registration.exposedTo.length > 0) {{
        registrationOptions.exposedTo = [...descriptor.registration.exposedTo];
      }}
      const tool: WebMCP.ModelContextTool = {{
        name: descriptor.name,
        ...("title" in descriptor ? {{ title: descriptor.title }} : {{}}),
        description: descriptor.description,
        inputSchema: descriptor.inputSchema,
        annotations: descriptor.annotations,
        execute: async (input, executionOptions) => {{
          if (executionOptions.signal.aborted) throw abortReason(executionOptions.signal);
          const currentHandlers = requireWebMCPHandlers(handlers, [descriptor.handler]);
          const result = await currentHandlers[descriptor.handler](input, {{
            signal: executionOptions.signal,
            toolName: descriptor.name,
          }});
          assertWebMCPJSONValue(result);
          JSON.stringify(result);
          return result;
        }},
      }};
      await modelContext.registerTool(tool, registrationOptions);
      registered.push(descriptor.name);
    }}
  }} catch (error) {{
    controller.abort(error);
    cleanupExternalListener();
    throw error;
  }}

  let disposed = false;
  return Object.freeze({{
    supported: true,
    registered: Object.freeze([...registered]),
    signal: controller.signal,
    dispose(reason?: unknown) {{
      if (disposed) return;
      disposed = true;
      controller.abort(reason);
      cleanupExternalListener();
    }},
  }});
}}
'''


def _react_adapter(manifest: dict[str, Any], manifest_hash: str, next_client: bool) -> str:
    runtime = _typescript_runtime(manifest, manifest_hash, next_client=next_client)
    names = json.dumps([tool["handler"] for tool in manifest.get("tools", [])], ensure_ascii=False)
    return runtime + f'''

import {{ useEffect, useRef, useState }} from "react";

export type WebMCPHookState = Readonly<{{
  status: "idle" | "registering" | "ready" | "unsupported" | "error";
  registered: readonly string[];
  error?: unknown;
}}>;

const WEBMCP_HANDLER_NAMES = {names} as const;

export function useWebMCPTools(
  handlers: WebMCPHandlers,
  enabled = true,
): WebMCPHookState {{
  const handlersRef = useRef(handlers);
  handlersRef.current = handlers;
  const [state, setState] = useState<WebMCPHookState>({{
    status: "idle",
    registered: Object.freeze([]),
  }});

  useEffect(() => {{
    if (!enabled) {{
      setState({{ status: "idle", registered: Object.freeze([]) }});
      return;
    }}

    let active = true;
    const lifecycle = new AbortController();
    setState({{ status: "registering", registered: Object.freeze([]) }});
    let stableHandlers: WebMCPHandlers;
    try {{
      stableHandlers = createWebMCPHandlerDelegates(
        () => handlersRef.current,
        WEBMCP_HANDLER_NAMES,
      );
    }} catch (error: unknown) {{
      setState({{ status: "error", registered: Object.freeze([]), error }});
      return () => {{
        active = false;
        lifecycle.abort(error);
      }};
    }}

    void registerWebMCPTools(stableHandlers, {{ signal: lifecycle.signal }})
      .then((registration) => {{
        if (!active) {{
          registration.dispose();
          return;
        }}
        setState({{
          status: registration.supported ? "ready" : "unsupported",
          registered: registration.registered,
        }});
      }})
      .catch((error: unknown) => {{
        if (active && !lifecycle.signal.aborted) {{
          setState({{ status: "error", registered: Object.freeze([]), error }});
        }}
      }});

    return () => {{
      active = false;
      lifecycle.abort();
    }};
  }}, [enabled]);

  return state;
}}
'''


def _vue_adapter(manifest: dict[str, Any], manifest_hash: str) -> str:
    runtime = _typescript_runtime(manifest, manifest_hash)
    names = json.dumps([tool["handler"] for tool in manifest.get("tools", [])], ensure_ascii=False)
    return runtime + f'''

import {{ onBeforeUnmount, onMounted, shallowRef }} from "vue";

export type WebMCPVueState = Readonly<{{
  status: "idle" | "registering" | "ready" | "unsupported" | "error";
  registered: readonly string[];
  error?: unknown;
}}>;

const WEBMCP_HANDLER_NAMES = {names} as const;

export function useWebMCPTools(getHandlers: () => WebMCPHandlers, enabled = true) {{
  const state = shallowRef<WebMCPVueState>({{
    status: "idle",
    registered: Object.freeze([]),
  }});
  let lifecycle: AbortController | undefined;

  onMounted(async () => {{
    if (!enabled) return;
    lifecycle = new AbortController();
    state.value = {{ status: "registering", registered: Object.freeze([]) }};
    try {{
      const stableHandlers = createWebMCPHandlerDelegates(getHandlers, WEBMCP_HANDLER_NAMES);
      const registration = await registerWebMCPTools(stableHandlers, {{
        signal: lifecycle.signal,
      }});
      if (!lifecycle.signal.aborted) {{
        state.value = {{
          status: registration.supported ? "ready" : "unsupported",
          registered: registration.registered,
        }};
      }}
    }} catch (error: unknown) {{
      if (!lifecycle.signal.aborted) {{
        state.value = {{ status: "error", registered: Object.freeze([]), error }};
      }}
    }}
  }});

  onBeforeUnmount(() => lifecycle?.abort());
  return {{ state, stop: () => lifecycle?.abort() }};
}}
'''


def _svelte_adapter(manifest: dict[str, Any], manifest_hash: str) -> str:
    runtime = _typescript_runtime(manifest, manifest_hash)
    names = json.dumps([tool["handler"] for tool in manifest.get("tools", [])], ensure_ascii=False)
    return runtime + f'''

import {{ onMount }} from "svelte";

export type WebMCPSvelteState = Readonly<{{
  status: "idle" | "registering" | "ready" | "unsupported" | "error";
  registered: readonly string[];
  error?: unknown;
}}>;

const WEBMCP_HANDLER_NAMES = {names} as const;

export function useWebMCPTools(
  getHandlers: () => WebMCPHandlers,
  onState: (state: WebMCPSvelteState) => void = () => {{}},
  enabled = true,
): void {{
  onMount(() => {{
    if (!enabled) return;
    const lifecycle = new AbortController();
    onState({{ status: "registering", registered: Object.freeze([]) }});
    let stableHandlers: WebMCPHandlers;
    try {{
      stableHandlers = createWebMCPHandlerDelegates(getHandlers, WEBMCP_HANDLER_NAMES);
    }} catch (error: unknown) {{
      onState({{ status: "error", registered: Object.freeze([]), error }});
      return () => lifecycle.abort(error);
    }}

    void registerWebMCPTools(stableHandlers, {{ signal: lifecycle.signal }})
      .then((registration) => {{
        if (!lifecycle.signal.aborted) {{
          onState({{
            status: registration.supported ? "ready" : "unsupported",
            registered: registration.registered,
          }});
        }}
      }})
      .catch((error: unknown) => {{
        if (!lifecycle.signal.aborted) {{
          onState({{ status: "error", registered: Object.freeze([]), error }});
        }}
      }});

    return () => lifecycle.abort();
  }});
}}
'''


def _angular_adapter(manifest: dict[str, Any], manifest_hash: str) -> str:
    runtime = _typescript_runtime(manifest, manifest_hash)
    return runtime + '''

import { Injectable, OnDestroy } from "@angular/core";

@Injectable({ providedIn: "root" })
export class WebMCPToolsService implements OnDestroy {
  private lifecycle?: AbortController;
  private registration?: WebMCPRegistration;

  async start(handlers: WebMCPHandlers): Promise<WebMCPRegistration> {
    this.stop();
    requireWebMCPHandlers(handlers);
    this.lifecycle = new AbortController();
    this.registration = await registerWebMCPTools(handlers, {
      signal: this.lifecycle.signal,
    });
    return this.registration;
  }

  stop(reason?: unknown): void {
    this.registration?.dispose(reason);
    this.registration = undefined;
    this.lifecycle?.abort(reason);
    this.lifecycle = undefined;
  }

  ngOnDestroy(): void {
    this.stop();
  }
}
'''


def generate_target(
    manifest: dict[str, Any],
    manifest_hash: str,
    target: str,
) -> str:
    """Generate one supported adapter target."""

    if target not in SUPPORTED_TARGETS:
        raise CodegenError(
            f"generation target must be one of: {', '.join(SUPPORTED_TARGETS)}"
        )
    if target == "vanilla-js":
        return generate_javascript(manifest, manifest_hash)
    if target == "typescript":
        return _typescript_runtime(manifest, manifest_hash)
    if target == "react":
        return _react_adapter(manifest, manifest_hash, False)
    if target == "next":
        return _react_adapter(manifest, manifest_hash, True)
    if target == "vue":
        return _vue_adapter(manifest, manifest_hash)
    if target == "svelte":
        return _svelte_adapter(manifest, manifest_hash)
    if target == "angular":
        return _angular_adapter(manifest, manifest_hash)
    raise CodegenError(f"unsupported generation target: {target}")
