// Generated by webmcp-codegen 3.0.0.
// Manifest SHA-256: e433661cdf93fbaf62b6327036fe0a3ec9a7e77962ffb46992e88df8c6539445
// Build-time semantics are intentionally omitted from browser registration.
// Bind only real application operations; this file does not invent business logic.

export const WEBMCP_MANIFEST_SHA256 = "e433661cdf93fbaf62b6327036fe0a3ec9a7e77962ffb46992e88df8c6539445";
const TOOL_DESCRIPTORS = Object.freeze([
  {
    "annotations": {
      "readOnlyHint": true,
      "untrustedContentHint": true
    },
    "description": "Read every sample evidence record, its explicit status, the selected record, saved annotations, and desk revision. Does not modify the desk.",
    "handler": "inspectEvidenceDesk",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {},
      "type": "object"
    },
    "name": "inspect_evidence_desk",
    "registration": {
      "exposedTo": []
    },
    "title": "Inspect evidence desk"
  },
  {
    "annotations": {
      "readOnlyHint": false,
      "untrustedContentHint": false
    },
    "description": "Select one sample evidence record for shared inspection without changing its observed, prepared, or blocked status.",
    "handler": "selectEvidenceRecord",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "expectedRevision": {
          "description": "Desk revision observed immediately before selection.",
          "minimum": 0,
          "type": "integer"
        },
        "recordId": {
          "description": "Identifier of the record to select.",
          "enum": [
            "wpt",
            "site-tools",
            "deployment"
          ],
          "type": "string"
        }
      },
      "required": [
        "recordId",
        "expectedRevision"
      ],
      "type": "object"
    },
    "name": "select_evidence_record",
    "registration": {
      "exposedTo": []
    },
    "title": "Select evidence record"
  },
  {
    "annotations": {
      "readOnlyHint": false,
      "untrustedContentHint": true
    },
    "description": "Attach one factual note to a sample evidence record without promoting or resolving its evidence status. Returns the saved note and unchanged status.",
    "handler": "annotateEvidenceRecord",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "expectedRevision": {
          "description": "Desk revision observed immediately before annotation.",
          "minimum": 0,
          "type": "integer"
        },
        "note": {
          "description": "Factual annotation to attach to the record.",
          "maxLength": 280,
          "minLength": 1,
          "type": "string"
        },
        "recordId": {
          "description": "Identifier of the evidence record to annotate.",
          "enum": [
            "wpt",
            "site-tools",
            "deployment"
          ],
          "type": "string"
        }
      },
      "required": [
        "recordId",
        "note",
        "expectedRevision"
      ],
      "type": "object"
    },
    "name": "annotate_evidence_record",
    "registration": {
      "exposedTo": []
    },
    "title": "Annotate evidence record"
  }
]);

export const WEBMCP_TOOL_NAMES = Object.freeze(
  TOOL_DESCRIPTORS.map((descriptor) => descriptor.name),
);

function abortReason(signal) {
  if (signal && "reason" in signal && signal.reason !== undefined) {
    return signal.reason;
  }
  return new DOMException("The operation was aborted.", "AbortError");
}

function jsonValueError(path, message) {
  return new TypeError(`WebMCP result is not JSON-safe at ${path}: ${message}`);
}

/**
 * Assert an intentional JSON value without relying on lossy JSON.stringify coercion.
 * @param {unknown} value
 * @param {string} path
 * @param {Set<object>} seen
 * @returns {unknown}
 */
export function assertWebMCPJSONValue(value, path = "$", seen = new Set()) {
  if (value === null) return value;
  const kind = typeof value;
  if (kind === "string" || kind === "boolean") return value;
  if (kind === "number") {
    if (!Number.isFinite(value)) throw jsonValueError(path, "number must be finite");
    return value;
  }
  if (kind !== "object") {
    throw jsonValueError(path, `unsupported ${kind} value`);
  }
  if (seen.has(value)) throw jsonValueError(path, "cyclic reference");
  seen.add(value);
  try {
    if (Array.isArray(value)) {
      if (Object.getOwnPropertySymbols(value).length > 0) {
        throw jsonValueError(path, "symbol-keyed array properties are unsupported");
      }
      const ownNames = Object.getOwnPropertyNames(value);
      const expectedNames = [
        ...Array.from({ length: value.length }, (_, index) => String(index)),
        "length",
      ];
      if (ownNames.length !== expectedNames.length ||
          expectedNames.some((name) => !ownNames.includes(name))) {
        throw jsonValueError(path, "arrays must be dense and have no extra properties");
      }
      for (let index = 0; index < value.length; index += 1) {
        assertWebMCPJSONValue(value[index], `${path}[${index}]`, seen);
      }
      return value;
    }

    const prototype = Object.getPrototypeOf(value);
    if (prototype !== Object.prototype && prototype !== null) {
      const name = value?.constructor?.name ?? "object";
      throw jsonValueError(path, `${name} instances must be converted to plain data`);
    }
    if (Object.getOwnPropertySymbols(value).length > 0) {
      throw jsonValueError(path, "symbol-keyed object properties are unsupported");
    }
    const enumerableNames = Object.keys(value);
    const ownNames = Object.getOwnPropertyNames(value);
    if (ownNames.length !== enumerableNames.length ||
        ownNames.some((name) => !enumerableNames.includes(name))) {
      throw jsonValueError(path, "object properties must be enumerable JSON fields");
    }
    for (const [key, child] of Object.entries(value)) {
      assertWebMCPJSONValue(child, `${path}.${key}`, seen);
    }
    return value;
  } finally {
    seen.delete(value);
  }
}

export function requireWebMCPHandlers(handlers, names = TOOL_DESCRIPTORS.map((item) => item.handler)) {
  if (!handlers || typeof handlers !== "object") {
    throw new TypeError("handlers must be an object keyed by manifest handler names");
  }
  for (const name of names) {
    if (typeof handlers[name] !== "function") {
      const descriptor = TOOL_DESCRIPTORS.find((item) => item.handler === name);
      const suffix = descriptor ? ` for ${descriptor.name}` : "";
      throw new TypeError(`Missing WebMCP application handler: ${name}${suffix}`);
    }
  }
  return handlers;
}

export function createWebMCPHandlerDelegates(getHandlers, names) {
  if (typeof getHandlers !== "function") {
    throw new TypeError("getHandlers must be a function");
  }
  requireWebMCPHandlers(getHandlers(), names);
  return Object.fromEntries(
    names.map((name) => [
      name,
      (input, context) => {
        const handlers = requireWebMCPHandlers(getHandlers(), [name]);
        return handlers[name](input, context);
      },
    ]),
  );
}

/** Register the generated toolset against real application handlers. */
export async function registerWebMCPTools(handlers, options = {}) {
  requireWebMCPHandlers(handlers);

  const modelContext = globalThis.document?.modelContext;
  if (typeof modelContext?.registerTool !== "function") {
    return Object.freeze({
      supported: false,
      registered: Object.freeze([]),
      dispose() {},
    });
  }

  const controller = new AbortController();
  const externalSignal = options?.signal;
  let externalAbortListener = null;
  if (externalSignal) {
    if (externalSignal.aborted) throw abortReason(externalSignal);
    externalAbortListener = () => controller.abort(abortReason(externalSignal));
    externalSignal.addEventListener("abort", externalAbortListener, { once: true });
  }

  const cleanupExternalListener = () => {
    if (externalSignal && externalAbortListener) {
      externalSignal.removeEventListener("abort", externalAbortListener);
      externalAbortListener = null;
    }
  };

  const registered = [];
  try {
    for (const descriptor of TOOL_DESCRIPTORS) {
      const registrationOptions = { signal: controller.signal };
      if (descriptor.registration.exposedTo.length > 0) {
        registrationOptions.exposedTo = [...descriptor.registration.exposedTo];
      }
      await modelContext.registerTool(
        {
          name: descriptor.name,
          ...(descriptor.title !== undefined ? { title: descriptor.title } : {}),
          description: descriptor.description,
          inputSchema: descriptor.inputSchema,
          annotations: descriptor.annotations,
          execute: async (input, executionOptions) => {
            const signal = executionOptions?.signal;
            if (signal?.aborted) throw abortReason(signal);
            const currentHandlers = requireWebMCPHandlers(handlers, [descriptor.handler]);
            const result = await currentHandlers[descriptor.handler](input, {
              signal,
              toolName: descriptor.name,
            });
            assertWebMCPJSONValue(result);
            JSON.stringify(result);
            return result;
          },
        },
        registrationOptions,
      );
      registered.push(descriptor.name);
    }
  } catch (error) {
    controller.abort(error);
    cleanupExternalListener();
    throw error;
  }

  let disposed = false;
  return Object.freeze({
    supported: true,
    registered: Object.freeze([...registered]),
    signal: controller.signal,
    dispose(reason) {
      if (disposed) return;
      disposed = true;
      controller.abort(reason);
      cleanupExternalListener();
    },
  });
}
